//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.AMIS.Core.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.AMIS.Core.Resource.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  đã tồn tại trong hệ thống.
        /// </summary>
        public static string ErrorDuplicated {
            get {
                return ResourceManager.GetString("ErrorDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  không được phép để trống.
        /// </summary>
        public static string ErrorEmpty {
            get {
                return ResourceManager.GetString("ErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  không đúng định dạng.
        /// </summary>
        public static string ErrorFormat {
            get {
                return ResourceManager.GetString("ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm tra trùng dữ liệu không thành công.
        /// </summary>
        public static string ExceptionCheckDuplicate {
            get {
                return ResourceManager.GetString("ExceptionCheckDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu không thành công.
        /// </summary>
        public static string ExceptionDelete {
            get {
                return ResourceManager.GetString("ExceptionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy dữ liệu nhân viên không thành công.
        /// </summary>
        public static string ExceptionEmployeePaging {
            get {
                return ResourceManager.GetString("ExceptionEmployeePaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất khẩu nhân viên không thành công.
        /// </summary>
        public static string ExceptionExport {
            get {
                return ResourceManager.GetString("ExceptionExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy dữ liệu không thành công.
        /// </summary>
        public static string ExceptionGetData {
            get {
                return ResourceManager.GetString("ExceptionGetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm dữ liệu không thành công.
        /// </summary>
        public static string ExceptionInsert {
            get {
                return ResourceManager.GetString("ExceptionInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy mã nhân viên mới không thành công.
        /// </summary>
        public static string ExceptionNewCode {
            get {
                return ResourceManager.GetString("ExceptionNewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa dữ liệu không thành công.
        /// </summary>
        public static string ExceptionUpdate {
            get {
                return ResourceManager.GetString("ExceptionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string OtherGender {
            get {
                return ResourceManager.GetString("OtherGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản.
        /// </summary>
        public static string PropBankAccount {
            get {
                return ResourceManager.GetString("PropBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh TK ngân hàng.
        /// </summary>
        public static string PropBankBranch {
            get {
                return ResourceManager.GetString("PropBankBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngân hàng.
        /// </summary>
        public static string PropBankName {
            get {
                return ResourceManager.GetString("PropBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string PropDateOfBirth {
            get {
                return ResourceManager.GetString("PropDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        public static string PropEmployeeCode {
            get {
                return ResourceManager.GetString("PropEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên.
        /// </summary>
        public static string PropFullName {
            get {
                return ResourceManager.GetString("PropFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        public static string PropGender {
            get {
                return ResourceManager.GetString("PropGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMND.
        /// </summary>
        public static string PropIdentityCard {
            get {
                return ResourceManager.GetString("PropIdentityCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Là khách hàng.
        /// </summary>
        public static string PropIsCustomer {
            get {
                return ResourceManager.GetString("PropIsCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Là nhà cung cấp.
        /// </summary>
        public static string PropIsGroup {
            get {
                return ResourceManager.GetString("PropIsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đơn vị.
        /// </summary>
        public static string PropOrganization {
            get {
                return ResourceManager.GetString("PropOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức danh.
        /// </summary>
        public static string PropPosition {
            get {
                return ResourceManager.GetString("PropPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ MISA để được hỗ trợ!.
        /// </summary>
        public static string UserMessage {
            get {
                return ResourceManager.GetString("UserMessage", resourceCulture);
            }
        }
    }
}
